language: java
jdk:
  - oraclejdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - tom.i7@hotmail.com
      - moragarcia2007@hotmail.com
      - juliancassi@hotmail.com
      - arilow@live.com.ar
    on_failure: always
